### ISSUE TITLE
path base obo file missing root.

### ISSUE THREAD

**Issue by cerivs** [PaulNSchofield/mpath#1]
http://eulep.pdn.cam.ac.uk/Pathology_Ontology/mpath.obo  is missing 
[Term]
id: MPATH:0
name: pathological entity
def: "Pathological structure or process" [Pathbase: Curation]

Has several classes that refer to this term.

**Comment by matentzn** [comment]
Use https://github.com/PaulNSchofield/mpath/blob/master/mpath.obo if still an issue
